// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPwYbls4a_RB6997YEDM6IfwmIUQE9rWk',
    appId: '1:110990285424:web:627d3eebf6af9579def2b5',
    messagingSenderId: '110990285424',
    projectId: 'my-chat-app-b2330',
    authDomain: 'my-chat-app-b2330.firebaseapp.com',
    storageBucket: 'my-chat-app-b2330.appspot.com',
    measurementId: 'G-8J2PR18XG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGHqvFPjxrOcuV1ym-8JpWzdA1ytRCAI0',
    appId: '1:110990285424:android:9955d8775e2c1fc4def2b5',
    messagingSenderId: '110990285424',
    projectId: 'my-chat-app-b2330',
    storageBucket: 'my-chat-app-b2330.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLwZIMmojm_NhKZRIr993ophQKZiL2nZ8',
    appId: '1:110990285424:ios:cc0c76753f3e6deddef2b5',
    messagingSenderId: '110990285424',
    projectId: 'my-chat-app-b2330',
    storageBucket: 'my-chat-app-b2330.appspot.com',
    iosBundleId: 'com.example.myChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLwZIMmojm_NhKZRIr993ophQKZiL2nZ8',
    appId: '1:110990285424:ios:6750fa2223fa6cd5def2b5',
    messagingSenderId: '110990285424',
    projectId: 'my-chat-app-b2330',
    storageBucket: 'my-chat-app-b2330.appspot.com',
    iosBundleId: 'com.example.myChatApp.RunnerTests',
  );
}
